site_name: CodeLimit Documentation
repo_url: https://github.com/getcodelimit/codelimit
theme:
  name: material
  palette:
  - scheme: slate
    primary: black
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - scheme: default
    primary: black
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - content.code.copy
extra_css:
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/asciinema-player.min.js
plugins:
  - glightbox:
      draggable: false
      background: none
      shadow: false
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
nav:
    - CodeLimit: 'index.md'
    - Getting Started:
      - 'getting-started/development-workflow.md'
      - 'getting-started/standalone-usage.md'
    - 'configuration.md'
    - 'why-function-length.md'
    - 'faq.md'
    - 'development.md'
